CREATE TABLE IF NOT EXISTS ACID_TRAB (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS RACA_COR (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ATESTANTE (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TIPO_MORTE (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FONT_INVEST (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ESCOLARIDADE (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ESTADO_CIVIL (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TIPO_GRAVIDEZ (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MORTE_PARTO (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OBITO_PUERPERIO (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TIPO_PARTO (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SEMANA_GESTACIONAL (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SIT_GESTACIONAL (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OCORRENCIA_OBITO_GEST (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS COD_MUN_OCOR (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS NUM_UF (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS UNIDADE_MEDIDA_IDADE (
    ID INTEGER PRIMARY KEY,
    TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MORTALIDADE_GERAL (
    ID SERIAL PRIMARY KEY,
    ACID_TRAB INTEGER,
    ATESTADO VARCHAR(255), 
    ATESTANTE INTEGER,
    CAUSA_CID VARCHAR(255), 
    FONT_INVEST INTEGER, 
    CID_MATERNO VARCHAR(255), 
    TIPO_MORTE INTEGER, 
    DATA_NASC DATE, 
    DATA_OBITO DATE, 
    ESCOLARIDADE INTEGER, 
    ESTADO_CIVIL INTEGER, 
    RACA_COR INTEGER, 
    COD_EST_OCOR INTEGER, 
    TIPO_GRAVIDEZ INTEGER, 
    HORA_OBITO TIME, 
    UNIDADE_MEDIDA_IDADE INTEGER,
    IDADE VARCHAR(255), 
    IDADE_MAE INTEGER, 
    LINHA_A VARCHAR(255), 
    LINHA_B VARCHAR(255), 
    LINHA_C VARCHAR(255), 
    LINHA_D VARCHAR(255), 
    LINHA_II VARCHAR(255), 
    LOCAL_OCORRENCIA INTEGER, 
    MORTE_PARTO INTEGER, 
    COD_MUN_OCOR INTEGER, 
    OBITO_GRAV INTEGER, 
    OBITO_PUERPERIO INTEGER, 
    TIPO_PARTO INTEGER,
    PESO_NASC DECIMAL(10, 2), 
    QTD_FILHO_MORTO INTEGER, 
    QTD_FILHO_VIVO INTEGER, 
    SEXO CHAR(1), 
    OBITO_FETAL INTEGER, 
    SIT_GESTACIONAL INTEGER, 
    OCORRENCIA_OBITO_GEST INTEGER,
    SEMANA_GESTACIONAL INTEGER,
    CONSTRAINT FK_SEMANA_GESTACIONAL
        FOREIGN KEY (SEMANA_GESTACIONAL) 
        REFERENCES SEMANA_GESTACIONAL(ID),
    CONSTRAINT FK_ACID_TRAB
        FOREIGN KEY (ACID_TRAB) 
        REFERENCES ACID_TRAB(ID),
    CONSTRAINT FK_OCORRENCIA_OBITO_GEST
        FOREIGN KEY (OCORRENCIA_OBITO_GEST) 
        REFERENCES OCORRENCIA_OBITO_GEST(ID),
    CONSTRAINT FK_ATESTANTE
        FOREIGN KEY (ATESTANTE) 
        REFERENCES ATESTANTE(ID),
    CONSTRAINT FK_FONT_INVEST
        FOREIGN KEY (FONT_INVEST) 
        REFERENCES FONT_INVEST(ID),
    CONSTRAINT FK_TIPO_MORTE
        FOREIGN KEY (TIPO_MORTE) 
        REFERENCES TIPO_MORTE(ID),
    CONSTRAINT FK_ESCOLARIDADE
        FOREIGN KEY (ESCOLARIDADE) 
        REFERENCES ESCOLARIDADE(ID),
    CONSTRAINT FK_ESTADO_CIVIL
        FOREIGN KEY (ESTADO_CIVIL) 
        REFERENCES ESTADO_CIVIL(ID),
    CONSTRAINT FK_RACA_COR
        FOREIGN KEY (RACA_COR) 
        REFERENCES RACA_COR(ID),
    CONSTRAINT FK_TIPO_GRAVIDEZ
        FOREIGN KEY (TIPO_GRAVIDEZ) 
        REFERENCES TIPO_GRAVIDEZ(ID),
    CONSTRAINT FK_MORTE_PARTO
        FOREIGN KEY (MORTE_PARTO) 
        REFERENCES MORTE_PARTO(ID),
    CONSTRAINT FK_OBITO_PUERPERIO
        FOREIGN KEY (OBITO_PUERPERIO) 
        REFERENCES OBITO_PUERPERIO(ID),
    CONSTRAINT FK_TIPO_PARTO
        FOREIGN KEY (TIPO_PARTO) 
        REFERENCES TIPO_PARTO(ID),
    CONSTRAINT FK_SIT_GESTACIONAL
        FOREIGN KEY (SIT_GESTACIONAL) 
        REFERENCES SIT_GESTACIONAL(ID),
    CONSTRAINT FK_COR_MUN_OCOR
        FOREIGN KEY (COD_MUN_OCOR) 
        REFERENCES COD_MUN_OCOR(ID),
    CONSTRAINT FK_NUM_UF
        FOREIGN KEY (COD_EST_OCOR) 
        REFERENCES NUM_UF(ID),
    CONSTRAINT FK_UNIDADE_MEDIDA_IDADE
        FOREIGN KEY (UNIDADE_MEDIDA_IDADE) 
        REFERENCES UNIDADE_MEDIDA_IDADE(ID)
);