INSERT INTO MORTALIDADE_GERAL (ACID_TRAB, ATESTADO, ATESTANTE, CAUSA_CID, FONT_INVEST, CID_MATERNO, TIPO_MORTE, DATA_NASC, DATA_OBITO, ESCOLARIDADE, ESTADO_CIVIL, RACA_COR, SEMANA_GESTACIONAL, COD_EST_OCOR, TIPO_GRAVIDEZ, HORA_OBITO, UNIDADE_MEDIDA_IDADE, IDADE, IDADE_MAE, LINHA_A, LINHA_B, LINHA_C, LINHA_D, LINHA_II, LOCAL_OCORRENCIA, MORTE_PARTO, COD_MUN_OCOR, OBITO_GRAV, OBITO_PUERPERIO, TIPO_PARTO, PESO_NASC, QTD_FILHO_MORTO, QTD_FILHO_VIVO, SEXO, OBITO_FETAL, SIT_GESTACIONAL, OCORRENCIA_OBITO_GEST) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);

INSERT INTO ACID_TRAB (ID, TYPE) VALUES (%s, %s);

INSERT INTO RACA_COR (ID, TYPE) VALUES (%s, %s);

INSERT INTO ATESTANTE (ID, TYPE) VALUES (%s, %s);

INSERT INTO TIPO_MORTE (ID, TYPE) VALUES (%s, %s);

INSERT INTO FONT_INVEST (ID, TYPE) VALUES (%s, %s);

INSERT INTO ESCOLARIDADE (ID, TYPE) VALUES (%s, %s);

INSERT INTO ESTADO_CIVIL (ID, TYPE) VALUES (%s, %s);

INSERT INTO TIPO_GRAVIDEZ (ID, TYPE) VALUES (%s, %s);

INSERT INTO MORTE_PARTO (ID, TYPE) VALUES (%s, %s);

INSERT INTO OBITO_PUERPERIO (ID, TYPE) VALUES (%s, %s);

INSERT INTO TIPO_PARTO (ID, TYPE) VALUES (%s, %s);

INSERT INTO SEMANA_GESTACIONAL (ID, TYPE) VALUES (%s, %s);

INSERT INTO SIT_GESTACIONAL (ID, TYPE) VALUES (%s, %s);

INSERT INTO OCORRENCIA_OBITO_GEST (ID, TYPE) VALUES (%s, %s);

INSERT INTO COD_MUN_OCOR (ID, NAME) VALUES (%s, %s);

INSERT INTO NUM_UF (ID, NAME) VALUES (%s, %s);

INSERT INTO UNIDADE_MEDIDA_IDADE (ID, TYPE) VALUES (%s, %s);